content/kontakt/members.json
The list of active members was a bit outdated, so i updated it. It should now be correct.
=> Updated list of members

config.toml, content/nyheter/2022-01-12-jubileum.md, content/nyheter/2022-02-08-jubileum-ctf.md, templates/base/footer.html, templates/base/header.html, templates/index.html, templates/nyheter.html, templates/shortcodes/buttons.html
This is to prepare for new update to Zola which will include backlinks support which might be useful in the future.
=> Fix internal links

.github/workflows/deploy.yml, config.toml
Remove zola check
Foreslår å fjerne denne da det ser ut til at Instagram blokker github fra å gjøre request til Instagram,
se https://github.com/fribyte-code/fribyte.no/actions/runs/3999867940/jobs/6864490876
=> Add instagram skip to config.toml

content/nyheter/2023-02-20-ctf.md
=> Typo CTF nyhet

content/dokumenter/handlingsplaner/handlingsplan-2023v.md
Just merge and delete branch if you are happy
=> Correct handlingsplan v23 title

content/kontakt/members.json
=> Makes Morten Linderud a guru

config.toml, templates/base/footer.html
- Lagt til GitHub i footeren.
- Erstattet "Utviklet av" med "Kildekode" som linker til dette repoet.
=> feat: Add GitHub to footer

config.toml, templates/base/footer.html
- Fikset bug med at vi brukte hovednavigasjon i footer istedenfor footer-nav.
- La til ekstra prop i footer-nav for å sjekke om siden er tilgjengelig på
engelsk.
=> fix: Use actual footer links and show that you are on `/dokumenter`

content/klienter.en.md, content/klienter.md, content/kontakt/members.json
updated our clients with the new ones in both norwegian and english.
=> :memo: update our clients

content/kontakt/members.json
added new members and sorted inactive members.
=> :memo: update memberlist

content/bli-medlem.en.md, content/bli-medlem.md
updated info about fribyte for those wanting to become a member, both in norwegian and english.
=> :memo: update info about fribyte

templates/base/default.html, templates/base/header.html
This PR is for fixing stuff the
[W3C validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Ffribyte.no%2Fkontakt%2F)
complains about. Might help us with #15.
- fix: Add doctype
- fix: Swap span with li
- fix: Remove defer
=> fix: Minor HTML stuff

content/tjenester.md
Swap use of square brackets and parenthesis to make link correct markdown link syntax
=> fix: link in tjenester.md

content/nyheter/2023-10-03-BOSKonferanse2023.md
Vi bør nok endre mer på denne senere, men det er en start.
Løser litt av. #47
=> :pencil: Enkel nyhet om Boskonf 2023

content/kontakt/members.json
Kan kanskje vente litt med å merge
=> :notebook: Oppdater medlemsliste etter utflukt

README.md
Documents `fribyte.no` in fribyte-code/wiki#1
=> docs: Update getting started and some formatting

content/bli-medlem.en.md, content/tjenester.md
Fant litt småfeil i både norske og engelske filer :sweat_smile:
=> :speech_balloon: fix text-errors

.github/workflows/pull-request.yml
Tenkte vi kunne ha en workflow som sjekker PRs også? Hva tenker dere?
=> :construction_worker: add PR-workflow checker

content/kontakt/members.json
Lagt til Lukas på fribyten nettsio
=> Lagt til meg sjølv på fribyten nettsio

content/kontakt/members.json
=> chore(members): Make myself inactive

sass/layouts/_news.scss, templates/nyheter.html
=> fix: Wrap dates properly and move them to the right-side

content/tjenester.en.md
=> Typo in English Services page

content/kontakt/members.json
To be merged when the Samordnet Registermelding goes through
=> Updates the roles of friByte members on the contact page

content/om.en.md, content/om.md, content/sosterorganisasjoner.en.md, content/sosterorganisasjoner.md
Closes issue #91 :sweat_smile: Have gotten permission for the 3 entries so far!
=> :sparkles: add pages for sisterorgs of friByte

content/kontakt/members.json, templates/kontakt.html
closes #96
Managed to sort the inactive members by position. Gave up on sorting by "left" attribute.
=> inactive members sorted by position

content/kontakt/members.json
Organizes the order, minor corrections
`jq '.[]."active"' content/kontakt/members.json | grep true | wc -l` 
We're now 32 active members!
=> Adds missing new members

content/om.en.md, content/om.md
Idk if any possibility of making it update automatically exists since we use markdown, but this will do as of now :sweat_smile:
=> :speech_balloon: Update year in about-section

content/kontakt/members.json
To be merged on 2024-12-01 if LGTM
=> New styre approved 2024-11-05

content/kontakt/members.json
- Christoffer Janson
- Lars Eirik Haukås
- Åsmund Aarvik
- Niklas Faraasen
- Julian Hjartholm Bosdal
- Duniya Mohamed Jami
- Mathilde Karlstad
=> Markere inaktive medlemmer
